### PR TITLE
Fix doc typo

### PR DESCRIPTION
**Pull request by chocolateboy**

### CODE REVIEW

**Comment by lopopolo** [comment]
Hi @chocolateboy thanks for fixing this 😄 

The crate documentation in `lib.rs` is also included in the crate `README.md`. Can you make the change to the README as well?

**Comment by chocolateboy** [comment]
@lopopolo Done (I assumed the README was generated/updated from the source by a build script).

**Comment by lopopolo** [comment]
> I assumed the README was generated/updated from the source by a build script

Unfortunately not 😞

**Comment by lopopolo** [comment]
Apologies for the slow build. Once GH-98 happens, builds will speed up significantly.

**Comment by lopopolo** [comment]
🎉 💎

**Pull request merged**
