### PR TITLE
 Bump tzdb from 0.4.0 to 0.5.0 

### PR DESCRIPTION
**Pull request by Kijewski**
It's-a me, @dependabot.

Please see the [changelog](https://docs.rs/tzdb/0.5.0/tzdb/changelog/index.html) for a full list of changes, or compare [`v0.4.5...v0.5.0`](https://github.com/Kijewski/tzdb/compare/v0.4.5...v0.5.0).

### CODE REVIEW

**Comment by lopopolo** [comment]
Thanks @Kijewski. Can you remove the `cargo update` commit? I prefer these off cycle dep upgrades to only touch the packages in the lockfile that they change.

**Comment by Kijewski** [comment]
Of course. I only made the first commit because vscode updates the dependencies automatically when you touch cargo.toml, and it didn't occur to me that I could simply  drop that first commit. :)

**Review by lopopolo — APPROVED** [review]
Thanks for the update and thank you for all the work you do in the Rust datetime ecosystem!

**Comment by Kijewski** [comment]
I updated spec-runner's and fuzz's Cargo.lock, so the CI is happy.

**Review by lopopolo — APPROVED** [review]

**Pull request merged**
