### PR TITLE
Implementation of Time's commodity methods

### PR DESCRIPTION
**Pull request by druzn3k**
This pull request _may_ solve issue #735 . I've also implemented the methods for the other weekdays, hope you don't mind. :)

### CODE REVIEW

**Comment by lopopolo** [comment]
@druzn3k It looks like the longer failed. You should be able to run `rake lint` to see what’s going on.

**Comment by lopopolo** [comment]
Linking GH-33.

**Comment by druzn3k** [comment]
@lopopolo I've corrected the lint problem and pushed/squashed everything. Now it should be good to go.

**Comment by lopopolo** [comment]
closes https://github.com/artichoke/artichoke/issues/735

**Pull request merged**
